name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include commands/logs if relevant.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: e.g., 0.1.0
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Python version, anything else.
